# Generated by Django 4.2.2 on 2023-07-04 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='image',
        ),
    ]
