# Generated by Django 4.2.2 on 2023-07-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entregas', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
